import {build} from 'esbuild';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync,mkdirSync} from 'node:fs';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
const sqlite=new DatabaseSync(':memory:');
const migrations=readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort();
sqlite.exec(readFileSync('drizzle/'+migrations[0],'utf8'));
sqlite.prepare('INSERT INTO transactions(id,user,period,date,type,amount,pocket,note) VALUES(?,?,?,?,?,?,?,?)').run('legacy','legacy-user','2025-01','2025-01-01','income',12345,'','Existing record');
for(const file of migrations.slice(1))sqlite.exec(readFileSync('drizzle/'+file,'utf8'));
assert.deepEqual({...sqlite.prepare("SELECT amount,debt_id FROM transactions WHERE id='legacy'").get()},{amount:12345,debt_id:null},'Migration preserves existing records');
const prepare=sql=>{let args=[];const statement={bind(...a){args=a;return statement;},async first(){return sqlite.prepare(sql).get(...args)??null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},async run(){return {meta:sqlite.prepare(sql).run(...args)};}};return statement;};
globalThis.__financeEnv={DB:{prepare,async batch(statements){sqlite.exec('BEGIN');try{const results=[];for(const s of statements)results.push(await s.run());sqlite.exec('COMMIT');return results;}catch(e){sqlite.exec('ROLLBACK');throw e;}}}};
globalThis.__financeUser={userId:'alice',displayName:'Alice',email:'alice@example.test'};
mkdirSync('work',{recursive:true});
await build({stdin:{contents:readFileSync('app/api/finance/route.ts','utf8'),loader:'ts',resolveDir:process.cwd()},tsconfigRaw:{},outfile:'work/finance-api-bundle.mjs',bundle:true,platform:'node',format:'esm',plugins:[{name:'test-environment',setup(b){b.onResolve({filter:/^(@\/lib\/|\.\/)(server|finance|payments)$/},a=>({path:'lib/'+a.path.split('/').at(-1)+'.ts',namespace:'source'}));b.onLoad({filter:/.*/,namespace:'source'},a=>({contents:readFileSync(a.path,'utf8'),loader:'ts'}));b.onResolve({filter:/^zod$/},()=>({path:'zod',external:true}));b.onResolve({filter:/^(cloudflare:workers|@\/app\/chatgpt-auth)$/},a=>({path:a.path,namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},a=>({contents:a.path==='cloudflare:workers'?'export const env=globalThis.__financeEnv;':'export const getChatGPTUser=async()=>globalThis.__financeUser;'}));}}]});
const api=await import('../work/finance-api-bundle.mjs');
async function request(method,payload,period='2026-08'){const response=await api[method](new Request('https://local.test/api/finance?period='+period,{method,headers:{origin:'https://local.test'},...(method==='GET'?{}:{body:JSON.stringify(payload)})}));return {status:response.status,data:await response.json()};}
const pockets=n=>Array.from({length:n},(_,i)=>({id:'p'+i,name:'Kantong '+i,kind:i===0?'monthly':'required',amount:100}));
const base={period:'2026-08',payday:1,opening:10000000,expected:0,pockets:pockets(10)};
assert.equal((await request('PUT',base)).status,200);
assert.equal((await request('PUT',{...base,pockets:pockets(11)})).status,403);
assert.equal((await request('PUT',{...base,sourcePeriod:base.period,period:'2026-09'})).status,200);
assert.equal((await request('PUT',{...base,sourcePeriod:base.period,period:'2026-09'})).status,409);
assert.equal((await request('GET')).data.budget.period,'2026-08');
const d={id:randomUUID(),name:'Laptop',total:600000,term:6,startPeriod:'2026-08',paidInstallments:1};
const debtPocket={id:'debt',name:'Laptop',kind:'installment',amount:100000,debtId:d.id};
const budget={...base,pockets:[...pockets(1),debtPocket],newDebts:[d]};
assert.equal((await request('PUT',budget)).status,200);
const t={id:randomUUID(),period:base.period,date:'2026-08-03',type:'expense',amount:100000,pocket:'debt',note:'Cicilan'};
assert.equal((await request('POST',t)).status,200);
assert.equal((await request('GET')).data.debts[0].paid,100000);
assert.equal((await request('POST',{...t,amount:200000})).status,200);
assert.equal((await request('POST',{...t,id:randomUUID(),amount:400000})).status,409);
assert.equal((await request('PUT',{...budget,pockets:[pockets(1)[0]]})).status,400,'Used debt pocket cannot be removed');
assert.equal((await request('PUT',{...budget,newDebts:[],period:'2026-09'})).status,200);
assert.equal((await request('POST',{...t,id:randomUUID(),period:'2026-09',date:'2026-09-03',amount:300000})).status,200);
assert.equal((await request('GET')).data.debts[0].paid,500000,'Payments aggregate across periods');
assert.equal((await request('POST',{...t,id:randomUUID(),amount:1})).status,409);
globalThis.__financeUser={userId:'bob',displayName:'Bob',email:'bob@example.test'};
assert.equal((await request('GET')).data.debts.length,0);
assert.equal((await request('PUT',{...budget,newDebts:[]})).status,400,'Cannot link another user debt');
assert.equal((await request('PUT',base)).status,200);
assert.equal((await request('POST',{...t,pocket:'p0'})).status,409,'Cannot overwrite another user transaction');
await request('DELETE',{id:t.id});
globalThis.__financeUser={userId:'alice',displayName:'Alice',email:'alice@example.test'};
assert.equal((await request('GET')).data.debts[0].paid,500000);
await request('DELETE',{id:t.id});assert.equal((await request('GET')).data.debts[0].paid,300000,'Deleting payment restores balance');
sqlite.prepare("INSERT INTO orders(id,user,amount,status,created,expires,mode) VALUES('premium','alice',19000,'paid',1,?,'production')").run(Math.floor(Date.now()/1000)+86400);
assert.equal((await request('PUT',{...base,period:'2026-10',pockets:pockets(20)})).status,200);
assert.equal((await request('PUT',{...base,period:'2026-10',pockets:pockets(21)})).status,400);
console.log('API regression checks passed: migrations, limits, copy, debt payments/edit/delete, cross-period and ownership.');
sqlite.close();
