import {char,int,text,tinyint,bigint,index,json,mysqlTable,primaryKey,varchar} from 'drizzle-orm/mysql-core';
export const budgets=mysqlTable('budgets',{user:varchar('user',{length:191}).notNull(),period:varchar('period',{length:7}).notNull(),data:json('data').notNull()},t=>[primaryKey({columns:[t.user,t.period]})]);
export const transactions=mysqlTable('transactions',{id:varchar('id',{length:64}).primaryKey(),user:varchar('user',{length:191}).notNull(),period:varchar('period',{length:7}).notNull(),date:varchar('date',{length:10}).notNull(),type:varchar('type',{length:16}).notNull(),amount:bigint('amount',{mode:'number',unsigned:true}).notNull(),pocket:varchar('pocket',{length:60}).notNull(),note:varchar('note',{length:120}).notNull(),debtId:varchar('debt_id',{length:64})},t=>[index('idx_transactions_user_period').on(t.user,t.period),index('idx_transactions_user_debt').on(t.user,t.debtId)]);
export const debts=mysqlTable('debts',{id:varchar('id',{length:64}).primaryKey(),user:varchar('user',{length:191}).notNull(),data:json('data').notNull()},t=>[index('idx_debts_user').on(t.user)]);
export const orders=mysqlTable('orders',{id:varchar('id',{length:64}).primaryKey(),user:varchar('user',{length:191}).notNull(),amount:bigint('amount',{mode:'number',unsigned:true}).notNull(),status:varchar('status',{length:32}).notNull(),url:varchar('url',{length:2048}),created:bigint('created',{mode:'number',unsigned:true}).notNull(),expires:bigint('expires',{mode:'number',unsigned:true}),mode:varchar('mode',{length:16}).notNull()},t=>[index('idx_orders_user_created').on(t.user,t.created)]);

export const authUsers=mysqlTable('auth_users',{id:varchar('id',{length:64}).primaryKey(),email:varchar('email',{length:254}).notNull().unique(),name:varchar('name',{length:80}).notNull(),passwordHash:varchar('password_hash',{length:255}),googleSub:varchar('google_sub',{length:255}).unique(),totpSecret:text('totp_secret'),totpLastStep:bigint('totp_last_step',{mode:'number'}).notNull().default(-1),created:bigint('created',{mode:'number',unsigned:true}).notNull()});
export const authSessions=mysqlTable('auth_sessions',{tokenHash:char('token_hash',{length:64}).primaryKey(),userId:varchar('user_id',{length:64}).notNull().references(()=>authUsers.id,{onDelete:'cascade'}),verified:tinyint('verified').notNull().default(0),created:bigint('created',{mode:'number',unsigned:true}).notNull(),expires:bigint('expires',{mode:'number',unsigned:true}).notNull(),pendingSecret:text('pending_secret'),pendingExpires:bigint('pending_expires',{mode:'number',unsigned:true})},t=>[index('idx_auth_sessions_user').on(t.userId),index('idx_auth_sessions_expiry').on(t.expires)]);
export const authRecoveryCodes=mysqlTable('auth_recovery_codes',{userId:varchar('user_id',{length:64}).notNull().references(()=>authUsers.id,{onDelete:'cascade'}),codeHash:char('code_hash',{length:64}).notNull()},t=>[primaryKey({columns:[t.userId,t.codeHash]})]);
export const authRateLimits=mysqlTable('auth_rate_limits',{bucketKey:char('bucket_key',{length:64}).primaryKey(),attempts:int('attempts',{unsigned:true}).notNull(),expires:bigint('expires',{mode:'number',unsigned:true}).notNull()},t=>[index('idx_auth_rate_expiry').on(t.expires)]);
export const authOauthStates=mysqlTable('auth_oauth_states',{stateHash:char('state_hash',{length:64}).primaryKey(),payload:text('payload').notNull(),expires:bigint('expires',{mode:'number',unsigned:true}).notNull()},t=>[index('idx_auth_oauth_expiry').on(t.expires)]);
