'use client';
import {useState,type FormEvent} from 'react';
import Link from 'next/link';
import {ShieldCheck} from 'lucide-react';
export default function SecurityForm({initialEnabled}:{initialEnabled:boolean}){
 const [enabled,setEnabled]=useState(initialEnabled),[secret,setSecret]=useState(''),[code,setCode]=useState(''),[codes,setCodes]=useState<string[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function action(name:string){setBusy(true);setError('');try{const result=await fetch('/api/auth/'+name,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({code})});const data=await result.json();if(!result.ok)throw new Error(data.error);if(name==='mfa-setup')setSecret(data.secret);if(name==='mfa-enable'){setEnabled(true);setSecret('');setCodes(data.codes);setCode('');}if(name==='mfa-disable'){setEnabled(false);setCodes([]);setCode('');}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function submit(e:FormEvent){e.preventDefault();void action(enabled?'mfa-disable':'mfa-enable');}
 return <main className="security-page card"><Link className="subtle-button" href="/">← Kembali ke ringkasan</Link><ShieldCheck className="mt-6" size={32}/><h1>Keamanan akun</h1><p>Verifikasi dua langkah menambahkan kode authenticator setelah password maupun login Google.</p><span className="status-tag">{enabled?'2FA aktif':'2FA belum aktif'}</span>{codes.length>0&&<section className="hint"><h2>Simpan kode pemulihan</h2><p>Kode ini hanya ditampilkan sekali. Simpan di tempat pribadi sebelum meninggalkan halaman. Setiap kode dapat dipakai sekali jika aplikasi authenticator tidak tersedia.</p><pre className="recovery-codes">{codes.join('\n')}</pre><button type="button" className="secondary" onClick={()=>{const blob=new Blob([codes.join('\n')],{type:'text/plain'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='kantong-rantau-kode-pemulihan.txt';a.click();URL.revokeObjectURL(url);}}>Unduh kode pemulihan</button></section>}{!enabled&&!secret&&<button className="primary mt-6" disabled={busy} onClick={()=>void action('mfa-setup')}>Aktifkan verifikasi dua langkah</button>}{secret&&<section className="hint"><h2>Tambahkan akun di authenticator</h2><p>Buka Google Authenticator atau aplikasi serupa. Pilih tambah akun dengan kunci penyiapan, gunakan nama Kantong Rantau dan jenis berbasis waktu.</p><code className="totp-secret">{secret}</code><p>Jangan bagikan kunci ini. Masukkan kode 6 digit yang muncul untuk mengaktifkan 2FA.</p></section>}{(secret||enabled)&&<form onSubmit={submit}><label className="field">{enabled?'Kode authenticator atau kode pemulihan untuk menonaktifkan 2FA':'Kode authenticator'}<input required autoComplete="one-time-code" value={code} maxLength={enabled?16:6} onChange={e=>setCode(e.target.value)}/></label><button className={enabled?'secondary':'primary'} disabled={busy}>{busy?'Memproses…':enabled?'Nonaktifkan 2FA':'Verifikasi dan aktifkan'}</button></form>}{error&&<p role="alert" className="error">{error}</p>}<p className="small muted mt-6">Perubahan keamanan memerlukan login dalam 10 menit terakhir. Mengaktifkan atau menonaktifkan 2FA mengakhiri sesi lain.</p></main>;
}
